server:
  port: 8084

spring:
  application:
    name: BOOKING-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/booking_service?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Praaks@02

    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: false
    register-with-eureka: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

resilience4j:
  circuitbreaker:
    instances:

      hotelService:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true

      userService:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true